-- Litemacro Marketplace Supabase setup / upgrade.
-- Run this in the Supabase SQL Editor for the Litemacro project.
--
-- This version does not use Discord OAuth. Uploads are anonymous and are
-- rate-limited by a local uploader id generated by the mod.

create extension if not exists pgcrypto;

create table if not exists public.marketplace_presets (
    id uuid primary key default gen_random_uuid(),
    created_at timestamptz not null default now(),
    slug text not null unique,
    name text not null,
    author_name text not null,
    description text not null default '',
    tags text[] not null default '{}',
    game_version text,
    litemacro_version text,
    likes_count integer not null default 0,
    downloads_count integer not null default 0,
    file_path text not null,
    published boolean not null default true,
    updated_at timestamptz not null default now(),
    author_user_id uuid,
    storage_bucket text not null default 'graphs',
    author_avatar_url text,
    uploader_install_id text,
    macro_json jsonb
);

alter table public.marketplace_presets add column if not exists slug text;
alter table public.marketplace_presets add column if not exists name text;
alter table public.marketplace_presets add column if not exists author_name text;
alter table public.marketplace_presets add column if not exists description text not null default '';
alter table public.marketplace_presets add column if not exists tags text[] not null default '{}';
alter table public.marketplace_presets add column if not exists game_version text;
alter table public.marketplace_presets add column if not exists litemacro_version text;
alter table public.marketplace_presets add column if not exists likes_count integer not null default 0;
alter table public.marketplace_presets add column if not exists downloads_count integer not null default 0;
alter table public.marketplace_presets add column if not exists file_path text;
alter table public.marketplace_presets add column if not exists published boolean not null default true;
alter table public.marketplace_presets add column if not exists updated_at timestamptz not null default now();
alter table public.marketplace_presets add column if not exists author_user_id uuid;
alter table public.marketplace_presets add column if not exists storage_bucket text not null default 'graphs';
alter table public.marketplace_presets add column if not exists author_avatar_url text;
alter table public.marketplace_presets add column if not exists uploader_install_id text;
alter table public.marketplace_presets add column if not exists macro_json jsonb;

alter table public.marketplace_presets alter column file_path set not null;
alter table public.marketplace_presets alter column published set default true;
alter table public.marketplace_presets alter column storage_bucket set default 'graphs';

create unique index if not exists marketplace_presets_slug_key on public.marketplace_presets (slug);
create index if not exists marketplace_presets_published_updated_idx on public.marketplace_presets (published, updated_at desc);
create index if not exists marketplace_presets_uploader_idx on public.marketplace_presets (uploader_install_id, created_at desc);

create table if not exists public.litemacro_marketplace_likes (
    preset_id uuid not null references public.marketplace_presets(id) on delete cascade,
    liker_install_id text not null,
    created_at timestamptz not null default now(),
    primary key (preset_id, liker_install_id)
);

create index if not exists litemacro_marketplace_likes_liker_idx on public.litemacro_marketplace_likes (liker_install_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists marketplace_presets_set_updated_at on public.marketplace_presets;
create trigger marketplace_presets_set_updated_at
before update on public.marketplace_presets
for each row execute function public.set_updated_at();

-- Remove old authenticated publish/sign-in helper functions from earlier marketplace builds.
drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text);
drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, boolean);
drop function if exists public.publish_marketplace_preset(text, text, text, text, text[], text, text, text, text, boolean);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean);
drop function if exists public.update_marketplace_preset_metadata(uuid, text, text, text[], text, text, boolean, text, text);
drop function if exists public.fetch_my_marketplace_presets();
drop function if exists public.fetch_my_marketplace_preset_likes();
drop function if exists public.toggle_marketplace_preset_like(uuid);
drop function if exists public.record_marketplace_download(uuid);
drop function if exists public.upsert_marketplace_profile(text, text);
drop function if exists public.submit_litemacro_marketplace_preset(text, text, text, text, text, text[], text, text, jsonb);
drop function if exists public.download_litemacro_marketplace_preset(uuid);
drop function if exists public.increment_preset_downloads(uuid);
drop function if exists public.like_litemacro_marketplace_preset(uuid, text);

create or replace function public.normalize_litemacro_tags(preset_tags text[])
returns text[]
language sql
immutable
as $$
    with normalized as (
        select distinct left(trim(lower(tag)), 32) as tag
        from unnest(coalesce(preset_tags, array[]::text[])) as tag
        where coalesce(trim(tag), '') <> ''
        limit 12
    ),
    collected as (
        select coalesce(array_agg(tag), array[]::text[]) as tags
        from normalized
    )
    select case
        when 'litemacro' = any(tags) then tags
        else array_prepend('litemacro', tags)
    end
    from collected;
$$;

create or replace function public.unique_litemacro_slug(base_slug text)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    normalized text;
    candidate text;
    suffix integer := 2;
begin
    normalized := regexp_replace(lower(coalesce(trim(base_slug), '')), '[^a-z0-9]+', '-', 'g');
    normalized := regexp_replace(normalized, '(^-+|-+$)', '', 'g');

    if normalized = '' then
        normalized := 'litemacro-macro';
    end if;

    normalized := left(normalized, 80);
    candidate := normalized;

    while exists (select 1 from public.marketplace_presets where slug = candidate) loop
        candidate := left(normalized, 76) || '-' || suffix::text;
        suffix := suffix + 1;
    end loop;

    return candidate;
end;
$$;

create or replace function public.submit_litemacro_marketplace_preset(
    uploader_install_id text,
    preset_slug text,
    preset_name text,
    preset_author_name text,
    preset_description text,
    preset_tags text[],
    preset_game_version text,
    preset_litemacro_version text,
    macro_json jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    normalized_uploader text;
    upload_count integer;
    remaining integer;
    preset_id uuid := gen_random_uuid();
    final_slug text;
    normalized_tags text[];
begin
    normalized_uploader := nullif(trim(coalesce(uploader_install_id, '')), '');
    if normalized_uploader is null then
        raise exception 'Uploader id is required.' using errcode = 'P0001';
    end if;

    if macro_json is null or jsonb_typeof(macro_json) <> 'object' then
        raise exception 'Macro JSON is required.' using errcode = 'P0001';
    end if;

    select count(*)
    into upload_count
    from public.marketplace_presets presets
    where presets.uploader_install_id = normalized_uploader;

    if upload_count >= 5 then
        return jsonb_build_object(
            'accepted', false,
            'upload_count', upload_count,
            'remaining', 0,
            'message', 'Upload limit reached. Each user can upload up to 5 macros.'
        );
    end if;

    final_slug := public.unique_litemacro_slug(preset_slug);
    normalized_tags := public.normalize_litemacro_tags(preset_tags);

    insert into public.marketplace_presets (
        id,
        slug,
        name,
        author_name,
        description,
        tags,
        game_version,
        litemacro_version,
        likes_count,
        downloads_count,
        storage_bucket,
        file_path,
        published,
        uploader_install_id,
        macro_json
    )
    values (
        preset_id,
        final_slug,
        left(coalesce(nullif(trim(preset_name), ''), final_slug), 96),
        left(coalesce(nullif(trim(preset_author_name), ''), 'Litemacro user'), 64),
        left(coalesce(preset_description, ''), 1200),
        normalized_tags,
        nullif(trim(coalesce(preset_game_version, '')), ''),
        nullif(trim(coalesce(preset_litemacro_version, '')), ''),
        0,
        0,
        'database',
        'database/' || preset_id::text || '.json',
        true,
        normalized_uploader,
        macro_json
    );

    upload_count := upload_count + 1;
    remaining := greatest(0, 5 - upload_count);

    return jsonb_build_object(
        'accepted', true,
        'upload_count', upload_count,
        'remaining', remaining,
        'message', 'Uploaded to Litemacro Marketplace.'
    );
end;
$$;

create or replace function public.download_litemacro_marketplace_preset(target_preset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    preset_json jsonb;
begin
    select macro_json
    into preset_json
    from public.marketplace_presets
    where id = target_preset_id
      and published = true
      and storage_bucket = 'database'
      and macro_json is not null;

    if preset_json is null then
        raise exception 'Marketplace macro JSON was not found.' using errcode = 'P0001';
    end if;

    return preset_json;
end;
$$;

create or replace function public.increment_preset_downloads(target_preset_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    update public.marketplace_presets
    set downloads_count = downloads_count + 1,
        updated_at = now()
    where id = target_preset_id
      and published = true;
end;
$$;

create or replace function public.like_litemacro_marketplace_preset(
    target_preset_id uuid,
    liker_install_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    normalized_liker text;
    liked_preset public.marketplace_presets;
begin
    normalized_liker := nullif(trim(coalesce(liker_install_id, '')), '');
    if normalized_liker is null then
        raise exception 'Liker id is required.' using errcode = 'P0001';
    end if;

    insert into public.litemacro_marketplace_likes (preset_id, liker_install_id)
    select target_preset_id, normalized_liker
    where exists (
        select 1
        from public.marketplace_presets
        where id = target_preset_id
          and published = true
    )
    on conflict do nothing;

    update public.marketplace_presets presets
    set likes_count = (
            select count(*)
            from public.litemacro_marketplace_likes likes
            where likes.preset_id = presets.id
        ),
        updated_at = now()
    where presets.id = target_preset_id
      and presets.published = true
    returning * into liked_preset;

    if liked_preset.id is null then
        raise exception 'Marketplace macro was not found.' using errcode = 'P0001';
    end if;

    return to_jsonb(liked_preset);
end;
$$;

alter table public.marketplace_presets enable row level security;
alter table public.litemacro_marketplace_likes enable row level security;

drop policy if exists "Public can read published marketplace presets" on public.marketplace_presets;
drop policy if exists "Public can read published presets" on public.marketplace_presets;
drop policy if exists "Owners can read their marketplace presets" on public.marketplace_presets;
drop policy if exists "authenticated users can read own presets" on public.marketplace_presets;
drop policy if exists "authenticated users can insert own presets" on public.marketplace_presets;
drop policy if exists "authenticated users can update own presets" on public.marketplace_presets;
drop policy if exists "authenticated users can delete own presets" on public.marketplace_presets;
drop policy if exists "Marketplace moderators can read all presets" on public.marketplace_presets;

create policy "Public can read published marketplace presets"
on public.marketplace_presets
for select
to anon, authenticated
using (published = true);

grant usage on schema public to anon, authenticated;
grant select on public.marketplace_presets to anon, authenticated;
revoke insert, update, delete on public.marketplace_presets from anon, authenticated;
revoke all on public.litemacro_marketplace_likes from anon, authenticated;
grant execute on function public.submit_litemacro_marketplace_preset(text, text, text, text, text, text[], text, text, jsonb) to anon, authenticated;
grant execute on function public.download_litemacro_marketplace_preset(uuid) to anon, authenticated;
grant execute on function public.increment_preset_downloads(uuid) to anon, authenticated;
grant execute on function public.like_litemacro_marketplace_preset(uuid, text) to anon, authenticated;

-- Optional public storage compatibility for older marketplace rows that still
-- point at files in the public "graphs" bucket.
insert into storage.buckets (id, name, public)
values ('graphs', 'graphs', true)
on conflict (id) do update set public = true;

drop policy if exists "graph files are publicly readable" on storage.objects;
create policy "graph files are publicly readable"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'graphs');

-- Supabase/PostgREST can keep an old function schema cached for a short time.
-- Reload it immediately so /rest/v1/rpc/submit_litemacro_marketplace_preset
-- becomes available after this script finishes.
notify pgrst, 'reload schema';

select
    'Litemacro marketplace RPC setup complete' as status,
    exists (
        select 1
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname = 'submit_litemacro_marketplace_preset'
    ) as submit_rpc_installed,
    exists (
        select 1
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname = 'download_litemacro_marketplace_preset'
    ) as download_rpc_installed,
    exists (
        select 1
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname = 'increment_preset_downloads'
    ) as download_count_rpc_installed,
    exists (
        select 1
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public'
          and p.proname = 'like_litemacro_marketplace_preset'
    ) as like_rpc_installed;
