org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=26.2
loader_version=0.19.3
fabric_loader_dependency=>=0.19.3
fabric_api_version=0.152.1+26.2
loom_version=1.15.5
minecraft_dependency=~26.2
java_dependency=>=25
minecraft_label=26.2.x

mod_version=1.0.54
maven_group=com.alfre
archives_base_name=Litemacro
build_owner=letgio
build_date=2026-05-08
